# Generated by Django 5.2.8 on 2025-11-25 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('pitch', 'Pitch'), ('hall', 'Hall'), ('gym', 'Gym')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_fixed', models.BooleanField(default=False, help_text='County fixtures – cannot be moved')),
                ('team_name', models.CharField(blank=True, max_length=100, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='scheduler.facility')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
