# Generated by Django 5.2.8 on 2026-02-18 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name_plural': 'facilities'},
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('juvenile_training', 'Juvenile Training'), ('adult_training', 'Adult Training'), ('gym_session', 'Gym Session'), ('match', 'Match'), ('championship', 'Championship Match'), ('meeting', 'Meeting'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('proposed', 'Proposed'), ('published', 'Published'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('age_group', models.CharField(blank=True, max_length=50)),
                ('usual_day', models.CharField(blank=True, max_length=20)),
                ('usual_time', models.TimeField(blank=True, null=True)),
                ('is_flexible', models.BooleanField(default=True, help_text='Flexible teams can be moved more easily by the solver')),
                ('usual_facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usual_teams', to='scheduler.facility')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='scheduler.team'),
        ),
    ]
