# Generated by Django 5.2.8 on 2026-02-19 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_alter_facility_options_event_event_type_event_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('juvenile_training', 'Juvenile Training'), ('adult_training', 'Adult Training'), ('gym_session', 'Gym Session'), ('match', 'Match'), ('championship', 'Championship Match'), ('meeting', 'Meeting'), ('other', 'Other')], default='other', max_length=30)),
                ('duration_minutes', models.IntegerField(help_text='Duration in minutes')),
                ('recurrence', models.CharField(choices=[('once', 'One-time'), ('weekly', 'Weekly')], default='weekly', max_length=20)),
                ('preferred_days', models.JSONField(default=list, help_text="e.g. ['tuesday', 'thursday']")),
                ('preferred_time_start', models.TimeField(help_text='Earliest acceptable start time')),
                ('preferred_time_end', models.TimeField(help_text='Latest acceptable end time')),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2)),
                ('schedule_from', models.DateField()),
                ('schedule_until', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('partial', 'Partially Scheduled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_facility', models.ForeignKey(blank=True, help_text='Leave blank for any suitable facility', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_requests', to='scheduler.facility')),
                ('scheduled_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_request', to='scheduler.event')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to='scheduler.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
