# Generated by Django 5.2.8 on 2026-03-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_bookingrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='type',
            field=models.CharField(choices=[('pitch', 'Pitch'), ('hall', 'Hall'), ('gym', 'Gym'), ('clubhouse', 'Clubhouse')], max_length=20),
        ),
    ]
