# Generated by Django 5.2.8 on 2026-03-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_alter_facility_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='target_date',
            field=models.DateField(blank=True, help_text='Specific date for one-time events', null=True),
        ),
    ]
