# Generated by Django 5.2.8 on 2026-03-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_bookingrequest_target_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='suitable_for',
            field=models.JSONField(blank=True, default=list, help_text="Event types this facility can host, e.g. ['match', 'adult_training']. Empty = all types."),
        ),
    ]
