# Generated by Django 5.2.8 on 2026-03-10 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_facility_suitable_for'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('coach', 'Coach'), ('viewer', 'Viewer')], default='viewer', max_length=20)),
                ('team', models.ForeignKey(blank=True, help_text='The team this coach manages (only relevant for coach role)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
